remote_theme: daattali/beautiful-jekyll@master
plugins:
- jekyll-remote-theme 

title: Art Style Recognizer
description: An image classification API that classifies 10 different types of Art Styles around the world.

author: Kaniz Fatema Nabila